#! /usr/bin/python

####### Problem Two #######
#Eacch new term in the Fibonacci sequence is generated by adding the previous two terms. 
#By starting with 1 and 2, the first 10 terms will be:
#
#    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
#find the sum of the even-valued terms.
###########################

x,y = 1,2 # Initialise these guys as the first two Fibonacci numbers
lim = 4e6 # Up to four million as the problem states
sm = 0 # Sum the even numbers

while x < lim:
    if x%2 == 0: sm += x
    tmp = x + y
    x = y
    y = tmp

print "The sum of the even Fibonancci terms up to four million is: %d" % sm

